### ISSUE TITLE
Spec failure due to rendering `abstract="no"` while `"no"` is already the default (want to skip if default)

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/metaschema#12]
This issue depends on this and requires configuration here:
* https://github.com/lutaml/lutaml-model/issues/110

Failing tests (sample only):
```
  1) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/allowed-values/allowed-values-basic_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" abstract="no">
         <schema-name>Metaschema Unit Test: allowed values</schema-name>
         <schema-version>1.0-milestone1</schema-version>
         <short-name>metaschema-allowed-values</short-name>
         <namespace>http://csrc.nist.gov/ns/metaschema/unit-test/allowed-values</namespace>
         <json-base-uri>http://csrc.nist.gov/ns/metaschema/unit-test/allowed-values</json-base-uri>
         <define-assembly scope="global">
           <formal-name>parent</formal-name>
           <description>parent assembly</description>
           <root-name>parent</root-name>
           <define-flag as-type="string" required="no">
             <formal-name>Small odd flag</formal-name>
             <description>Odd integers from 1 to 11 inclusive</description>
             <constraint>
               <allowed-values level="ERROR" allow-other="no" extensible="external">
                 <enum>One</enum>
                 <enum>Three</enum>
                 <enum>Five</enum>
                 <enum>Seven</enum>
                 <enum>Nine</enum>
                 <enum>Eleven</enum>
               </allowed-values>
             </constraint>
           </define-flag>
           <model>
             <field min-occurs="0" max-occurs="1" in-xml="WRAPPED">
               <group-as in-json="SINGLETON_OR_ARRAY" in-xml="UNGROUPED"/>
             </field>
             <assembly min-occurs="0" max-occurs="1">
               <group-as in-json="SINGLETON_OR_ARRAY" in-xml="UNGROUPED"/>
             </assembly>
           </model>
         </define-assembly>
         <define-assembly scope="global">
           <formal-name>child</formal-name>
           <description>child assembly</description>
           <flag required="no"/>
           <model>
             <field min-occurs="0" max-occurs="1" in-xml="WRAPPED"/>
           </model>
         </define-assembly>
         <define-field as-type="string" scope="global" collapsible="no">
           <formal-name>Date</formal-name>
           <description>One of several 2020 dates</description>
           <constraint>
             <allowed-values level="ERROR" allow-other="no" extensible="external">
               <enum>New Year's Day 2020</enum>
               <enum>Leap Day 2020</enum>
               <enum>July Fourth 2020</enum>
             </allowed-values>
           </constraint>
         </define-field>
         <define-flag as-type="string" scope="global">
           <formal-name>Small even flag</formal-name>
           <description>Even integers from 2 to 10 inclusive</description>
           <constraint>
             <allowed-values level="ERROR" allow-other="no" extensible="external">
               <enum>Two</enum>
               <enum>Four</enum>
               <enum>Six</enum>
               <enum>Eight</enum>
               <enum>Ten</enum>
             </allowed-values>
           </constraint>
         </define-flag>
       </METASCHEMA>
               actual node  : <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0">
          <schema-name>Metaschema Unit Test: allowed values</schema-name>
          <schema-version>1.0-milestone1</schema-version>
          <short-name>metaschema-allowed-values</short-name>
          <namespace>http://csrc.nist.gov/ns/metaschema/unit-test/allowed-values</namespace>
          <json-base-uri>http://csrc.nist.gov/ns/metaschema/unit-test/allowed-values</json-base-uri>
          <define-assembly name="parent">
             <formal-name>parent</formal-name>
             <description>parent assembly</description>
             <root-name>parent</root-name>
             <define-flag name="odd-flag" as-type="positive-integer" required="yes">
                <formal-name>Small odd flag</formal-name>
                <description>Odd integers from 1 to 11 inclusive</description>
                <constraint>
                   <allowed-values>
                      <enum value="1">One</enum>
                      <enum value="3">Three</enum>
                      <enum value="5">Five</enum>
                      <enum value="7">Seven</enum>
                      <enum value="9">Nine</enum>
                      <enum value="11">Eleven</enum>
                   </allowed-values>
                </constraint>
             </define-flag>
             <model>
                <field ref="field-date" max-occurs="unbounded">
                   <group-as name="field-dates"/>
                </field>
                <assembly ref="child" max-occurs="unbounded">
                   <group-as name="children"/>
                </assembly>
             </model>
          </define-assembly>
          <define-assembly name="child">
             <formal-name>child</formal-name>
             <description>child assembly</description>
             <flag ref="even-flag"/>
             <model>
                <field ref="field-date" min-occurs="1"/>
             </model>
          </define-assembly>
          <define-field name="field-date" as-type="date">
             <formal-name>Date</formal-name>
             <description>One of several 2020 dates</description>
             <constraint>
                <allowed-values target=".">
                   <enum value="2020-01-01">New Year's Day 2020</enum>
                   <enum value="2020-02-29">Leap Day 2020</enum>
                   <enum value="2020-07-04">July Fourth 2020</enum>
                </allowed-values>
             </constraint>
          </define-field>
          <define-flag name="even-flag" as-type="positive-integer">
             <formal-name>Small even flag</formal-name>
             <description>Even integers from 2 to 10 inclusive</description>
             <constraint>
                <allowed-values>
                   <enum value="2">Two</enum>
                   <enum value="4">Four</enum>
                   <enum value="6">Six</enum>
                   <enum value="8">Eight</enum>
                   <enum value="10">Ten</enum>
                </allowed-values>
             </constraint>
          </define-flag>
       </METASCHEMA>
               diff from    : abstract="no"
               diff to      : 
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  2) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/choice/choice-multiple_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" abstract="no">
         <schema-name>Metaschema Unit Test: choice multiple choices</schema-name>
         <schema-version>1.0</schema-version>
         <short-name>json-value-key-label</short-name>
         <namespace>http://csrc.nist.gov/ns/metaschema/unit-test/choice</namespace>
         <json-base-uri>http://csrc.nist.gov/ns/metaschema/unit-test/choice</json-base-uri>
         <define-assembly scope="global">
           <formal-name>parent</formal-name>
           <description>parent assembly</description>
           <root-name>parent</root-name>
           <model>
             <define-assembly min-occurs="0" max-occurs="1">
               <formal-name>child</formal-name>
               <description>child assembly</description>
               <group-as in-json="SINGLETON_OR_ARRAY" in-xml="UNGROUPED"/>
               <model>
                 <define-field as-type="string" collapsible="no" min-occurs="0" max-occurs="1" in-xml="WRAPPED"/>
                 <choice>
                   <define-assembly min-occurs="0" max-occurs="1"/>
                   <define-assembly min-occurs="0" max-occurs="1"/>
                   <define-assembly min-occurs="0" max-occurs="1"/>
                 </choice>
                 <choice>
                   <define-assembly min-occurs="0" max-occurs="1"/>
                   <define-assembly min-occurs="0" max-occurs="1"/>
                   <define-assembly min-occurs="0" max-occurs="1"/>
                 </choice>
                 <choice>
                   <define-assembly min-occurs="0" max-occurs="1"/>
                   <define-assembly min-occurs="0" max-occurs="1"/>
                   <define-assembly min-occurs="0" max-occurs="1"/>
                 </choice>
               </model>
             </define-assembly>
           </model>
         </define-assembly>
       </METASCHEMA>
               actual node  : <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0">
           <schema-name>Metaschema Unit Test: choice multiple choices</schema-name>
           <schema-version>1.0</schema-version>
           <short-name>json-value-key-label</short-name>
           <namespace>http://csrc.nist.gov/ns/metaschema/unit-test/choice</namespace>
           <json-base-uri>http://csrc.nist.gov/ns/metaschema/unit-test/choice</json-base-uri>
     
           <define-assembly name="parent">
               <formal-name>parent</formal-name>
               <description>parent assembly</description>
               <root-name>parent</root-name>
               <model>
                   <define-assembly name="child" min-occurs="0" max-occurs="unbounded">
                       <formal-name>child</formal-name>
                       <description>child assembly</description>
                       <group-as name="children" in-json="ARRAY"/>
                       <model>
                           <define-field name="non-choice" min-occurs="1"/>
                           <choice>
                               <define-assembly name="choice-1-1"/>
                               <define-assembly name="choice-1-2"/>
                               <define-assembly name="choice-1-3"/>
                           </choice>
                           <choice>
                               <define-assembly name="choice-2-1"/>
                               <define-assembly name="choice-2-2"/>
                               <define-assembly name="choice-2-3"/>
                           </choice>
                           <choice>
                               <define-assembly name="choice-3-1" min-occurs="1"/>
                               <define-assembly name="choice-3-2" min-occurs="1"/>
                               <define-assembly name="choice-3-3" min-occurs="1"/>
                           </choice>
                       </model>
                   </define-assembly>
               </model>
           </define-assembly>
       </METASCHEMA>
               diff from    : abstract="no"
               diff to      : 
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'
```

**Comment by ronaldtse** [comment]
This is fixed in:
* https://github.com/lutaml/lutaml-model/issues/110

Thank you @HassanAkbar !
