### ISSUE TITLE
Fix remaining spec failures due to missing `mixed: true` option

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/metaschema#13]
The only remaining failing specs are these.

These happen in the `<description>` tags (there are many) as these contain rich text. Rich text nodes need to be handled using the `mixed: true` option in lutaml-model.

```
Failures:

  1) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/group-as/group-as-misc_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST SP
                      800-60</a>
               actual node  : <description>Contains details about one information type that is stored, processed, or
                      transmitted by the system, such as privacy information, and those defined in <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST SP
                      800-60</a>.</description>
               diff from    : <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST SP
                      800-60</a>
               diff to      : Contains details about one information type that is stored, processed, or
                      transmitted by the system, such as privacy information, and those defined in 
     
       DIFF 2: expected node: <code>system</code>
               actual node  : <description>An identifier qualified by the given identification
                            <code>system</code> used, such as NIST SP 800-60.</description>
               diff from    : <code>system</code>
               diff to      : An identifier qualified by the given identification
                            
     
       DIFF 3: expected node: <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST SP 800-60 Volume
                                  2</a>
               actual node  : <p>The current allowed values are based on those identified in <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST SP 800-60 Volume
                                  2</a>
                            </p>
               diff from    : <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST SP 800-60 Volume
                                  2</a>
               diff to      : The current allowed values are based on those identified in 
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  2) Metaschema XML round-trip conversion with file metaschema/examples/computer-example.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <code>at</code>
               actual node  : <description>The type motherboard layout, <code>at</code>, <code>atx</code>, <code>mini-itx</code> or an alternative.</description>
               diff from    : <code>at</code>
               diff to      : The type motherboard layout, 
     
       DIFF 2: expected node: <code>x86</code>
               actual node  : <description>The Instruction Set Architecture (ISA) of the processor, <code>x86</code>, <code>x86-64</code>, <code>arm</code>, or an alternative.</description>
               diff from    : <code>x86</code>
               diff to      : The Instruction Set Architecture (ISA) of the processor, 
     
       DIFF 3: expected node: <code>pata</code>
               actual node  : <description>The type of ATA socket on the motherboard , <code>pata</code> (parallel ATA), <code>sata</code> (Serial ATA), or an alternative.</description>
               diff from    : <code>pata</code>
               diff to      : The type of ATA socket on the motherboard , 
     
       DIFF 4: expected node: <code>pci</code>
               actual node  : <description>The type of expansion card on a motherboard of a computer, such as <code>pci</code> (PCI, e.g. Peripheral Component Interconnect), <code>pcie</code> (PCI Express), or an alternative.</description>
               diff from    : <code>pci</code>
               diff to      : The type of expansion card on a motherboard of a computer, such as 
     
       DIFF 5: expected node: <allowed-values target="(motherboard|motherboard/cpu|motherboard/memory|motherboard/expansion-card|usb-device)/prop[not(@ns) or @ns=('http://example.com/ns/computer')]/@name">
         <enum value="model">CPU model</enum>
       </allowed-values>
               actual node  : <is-unique target="usb-device">
                       <formal-name>Unique USB Device UUID</formal-name>
                       <description>Ensures that each USB device has a unique UUID.</description>
                       <key-field target="@uuid"/>
                   </is-unique>
               diff from    : allowed-values
               diff to      : is-unique
     
       DIFF 6: expected node: <a href="https://datatracker.ietf.org/doc/html/rfc3986#section-4.3">absolute URI</a>
               actual node  : <p>This value must be an <a href="https://datatracker.ietf.org/doc/html/rfc3986#section-4.3">absolute URI</a> that serves as a naming system identifier.</p>
               diff from    : <a href="https://datatracker.ietf.org/doc/html/rfc3986#section-4.3">absolute URI</a>
               diff to      : This value must be an 
     
       DIFF 7: expected node: <code>ns</code>
               actual node  : <p>When a <code>ns</code> is not provided, its value should be assumed to be <code>http://example.com/ns/computer</code> and the name should be a name defined by this model.</p>
               diff from    : <code>ns</code>
               diff to      : When a 
     
       DIFF 8: expected node: <code>name</code>
               actual node  : <description>A textual label that provides a sub-type or characterization of the
                       property's <code>name</code>.</description>
               diff from    : <code>name</code>
               diff to      : A textual label that provides a sub-type or characterization of the
                       property's 
     
       DIFF 9: expected node: <code>name</code>
               actual node  : <p>This can be used to further distinguish or discriminate between the semantics of multiple properties of the same object with the same <code>name</code> and <code>ns</code>, or to group properties into categories.</p>
               diff from    : <code>name</code>
               diff to      : This can be used to further distinguish or discriminate between the semantics of multiple properties of the same object with the same 
     
       DIFF 10: expected node: <code>class</code>
               actual node  : <p>A <code>class</code> can be used in validation rules to express extra constraints over named items of a specific <code>class</code> value. It is available for grouping, but unlike <code>group</code> is not expected specifically to designate any group membership as such.</p>
               diff from    : <code>class</code>
               diff to      : A 
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

Finished in 0.25882 seconds (files took 0.15556 seconds to load)
62 examples, 2 failures
```

**Comment by ronaldtse** [comment]
Done in #14 .
