### ISSUE TITLE
Fix round-trip specs

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/metaschema#3]
There are 17 specs out of 60 odd that are failing:

```
.F...F.F.............F.F.F..............FF.........F.FFFFF.FFF

Failures:

  1) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/allowed-values/allowed-values-basic_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <assembly ref="child" max-occurs="unbounded">
               <group-as name="children"/>
             </assembly>
               actual node  : <field ref="field-date" max-occurs="unbounded">
                   <group-as name="field-dates"/>
                </field>
               diff from    : assembly
               diff to      : field
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  2) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/collapsible/collapsible-no-op_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <define-field as-type="string" name="prop">
           <formal-name>prop</formal-name>
           <description>prop field</description>
         </define-field>
               actual node  : <define-field name="prop" as-type="string" collapsible="yes">
             <formal-name>prop</formal-name>
             <description>prop field</description>
          </define-field>
               diff from    : 
               diff to      : collapsible="yes"
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  3) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/collapsible/collapsible_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <define-field as-type="string" name="prop">
           <formal-name>prop</formal-name>
           <description>prop field</description>
           <define-flag name="name">
             <formal-name>A simple flag</formal-name>
             <description>A simpleflag</description>
           </define-flag>
         </define-field>
               actual node  : <define-field name="prop" as-type="string" collapsible="yes">
             <formal-name>prop</formal-name>
             <description>prop field</description>
             <define-flag name="name">
                <formal-name>A simple flag</formal-name>
                <description>A simpleflag</description>
             </define-flag>
          </define-field>
               diff from    : 
               diff to      : collapsible="yes"
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  4) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/dates-times/datatypes-date_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <assembly ref="child" max-occurs="unbounded">
               <group-as name="children"/>
             </assembly>
               actual node  : <field ref="field-date" max-occurs="unbounded">
                   <group-as name="field-dates"/>
                </field>
               diff from    : assembly
               diff to      : field
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  5) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/dates-times/datatypes-datetime-no-tz_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <assembly ref="child" max-occurs="unbounded">
               <group-as name="children"/>
             </assembly>
               actual node  : <field ref="field-datetime-notz" max-occurs="unbounded">
                   <group-as name="field-datetimes-notz"/>
                </field>
               diff from    : assembly
               diff to      : field
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  6) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/dates-times/datatypes-datetime_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <assembly ref="child" max-occurs="unbounded">
               <group-as name="children"/>
             </assembly>
               actual node  : <field ref="field-datetime" max-occurs="unbounded">
                   <group-as name="field-datetimes"/>
                </field>
               diff from    : assembly
               diff to      : field
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  7) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/group-as/group-as-misc_metaschema.xml provides identical attribute access
     Failure/Error: parsed = Metaschema::Root.from_xml(xml_string)
     
     NoMethodError:
       undefined method `attributes' for nil
     # ./spec/metaschema_spec.rb:38:in `block (5 levels) in <top (required)>'

  8) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/group-as/group-as-misc_metaschema.xml performs lossless round-trip conversion
     Failure/Error: parsed = Metaschema::Root.from_xml(xml_string)
     
     NoMethodError:
       undefined method `attributes' for nil
     # ./spec/metaschema_spec.rb:50:in `block (5 levels) in <top (required)>'

  9) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/global-and-local_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <flag ref="global-flag"/>
               actual node  : <define-flag name="local-flag" as-type="token">
                <formal-name>Flag defined locally</formal-name>
                <description>Has a local definition</description>
             </define-flag>
               diff from    : flag
               diff to      : define-flag
     
       DIFF 2: expected node: <define-assembly name="global-assembly">
           <formal-name>Assembly defined globally</formal-name>
           <description>Has a global definition</description>
           <model>
             <field ref="global-field"/>
             <define-field as-type="string" name="local-field2">
               <formal-name>Field defined locally</formal-name>
               <description>Has a local definition</description>
             </define-field>
           </model>
         </define-assembly>
               actual node  : <define-flag name="global-flag" as-type="token">
             <formal-name>Flag defined globally</formal-name>
             <description>Has a global definition</description>
          </define-flag>
               diff from    : define-assembly
               diff to      : define-flag
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  10) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/global-and-scoped-local_metaschema.xml performs lossless round-trip conversion
      Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
      
        DIFF 1: expected node: <flag ref="global-flag"/>
                actual node  : <define-flag name="local-flag" as-type="string">
                 <formal-name>Flag defined locally</formal-name>
                 <description>Has a local definition</description>
              </define-flag>
                diff from    : flag
                diff to      : define-flag
      
        DIFF 2: expected node: <define-assembly name="top-level-local-assembly" scope="local">
            <formal-name>Assembly defined with scope='local', at top level</formal-name>
            <description>Should result as local</description>
            <model>
              <field ref="top-level-local-field"/>
              <field ref="global-field"/>
            </model>
          </define-assembly>
                actual node  : <define-field name="top-level-local-field" as-type="string" scope="local">
              <formal-name>Field defined with scope='local', at top level</formal-name>
              <description>Should result in a local definition</description>
           </define-field>
                diff from    : define-assembly
                diff to      : define-field
      # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  11) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/modular_metaschema.xml provides identical attribute access
      Failure/Error: parsed = Metaschema::Root.from_xml(xml_string)
      
      NoMethodError:
        undefined method `attributes' for nil
      # ./spec/metaschema_spec.rb:38:in `block (5 levels) in <top (required)>'

  12) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/modular_metaschema.xml performs lossless round-trip conversion
      Failure/Error: parsed = Metaschema::Root.from_xml(xml_string)
      
      NoMethodError:
        undefined method `attributes' for nil
      # ./spec/metaschema_spec.rb:50:in `block (5 levels) in <top (required)>'

  13) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/modules/module_metaschema.xml provides identical attribute access
      Failure/Error: parsed = Metaschema::Root.from_xml(xml_string)
      
      NoMethodError:
        undefined method `attributes' for nil
      # ./spec/metaschema_spec.rb:38:in `block (5 levels) in <top (required)>'

  14) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/modules/module_metaschema.xml performs lossless round-trip conversion
      Failure/Error: parsed = Metaschema::Root.from_xml(xml_string)
      
      NoMethodError:
        undefined method `attributes' for nil
      # ./spec/metaschema_spec.rb:50:in `block (5 levels) in <top (required)>'

  15) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/token/datatypes-token_metaschema.xml performs lossless round-trip conversion
      Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
      
        DIFF 1: expected node: <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0">
          <schema-name>Metaschema Unit Test: Token Datatype</schema-name>
          <schema-version>1.0-milestone2</schema-version>
          <short-name>metaschema-datatypes-token</short-name>
          <namespace>http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-uri</namespace>
          <json-base-uri>http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-uri</json-base-uri>
          <define-assembly name="parent">
            <formal-name>parent</formal-name>
            <description>parent assembly</description>
            <root-name>parent</root-name>
            <define-flag name="token-flag" as-type="token" required="yes">
              <formal-name>A metaschema 'token', a string without spaces suitable for use as a key value)</formal-name>
              <description>Corresponds to XML NCName (no-colon name).</description>
            </define-flag>
            <model>
              <field ref="token-field" max-occurs="unbounded">
                <group-as name="token-fields"/>
              </field>
            </model>
          </define-assembly>
          <define-field as-type="token" name="token-field">
            <formal-name>A metaschema 'token', a string without spaces for use as a key value</formal-name>
            <description>Corresponds to XML NCName (no-colon name).</description>
          </define-field>
        </METASCHEMA>
                actual node  : <METASCHEMA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.0 ../../../toolchains/xslt-M4/validate/metaschema.xsd">
          <schema-name>Metaschema Unit Test: Token Datatype</schema-name>
          <schema-version>1.0-milestone2</schema-version>
          <short-name>metaschema-datatypes-token</short-name>
          <namespace>http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-uri</namespace>
          <json-base-uri>http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-uri</json-base-uri>
         
          <define-assembly name="parent">
            <formal-name>parent</formal-name>
            <description>parent assembly</description>
            <root-name>parent</root-name>
            <define-flag name="token-flag" as-type="token" required="yes">
              <formal-name>A metaschema 'token', a string without spaces suitable for use as a key value)</formal-name>
              <description>Corresponds to XML NCName (no-colon name).</description>
            </define-flag>
            <model>
              <field ref="token-field" max-occurs="unbounded">
                <group-as name="token-fields"/>
              </field>
            </model>
          </define-assembly>
      
          <define-field name="token-field" as-type="token">
            <formal-name>A metaschema 'token', a string without spaces for use as a key value</formal-name>
            <description>Corresponds to XML NCName (no-colon name).</description>
          </define-field>
          
        </METASCHEMA>
                diff from    : 
                diff to      : schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.0 ../../../toolchains/xslt-M4/validate/metaschema.xsd"
      # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'

  16) Metaschema XML round-trip conversion with file metaschema/examples/computer-example.xml provides identical attribute access
      Failure/Error: parsed = Metaschema::Root.from_xml(xml_string)
      
      NoMethodError:
        undefined method `attributes' for nil
      # ./spec/metaschema_spec.rb:38:in `block (5 levels) in <top (required)>'

  17) Metaschema XML round-trip conversion with file metaschema/examples/computer-example.xml performs lossless round-trip conversion
      Failure/Error: parsed = Metaschema::Root.from_xml(xml_string)
      
      NoMethodError:
        undefined method `attributes' for nil
      # ./spec/metaschema_spec.rb:50:in `block (5 levels) in <top (required)>'

Finished in 0.29253 seconds (files took 0.09808 seconds to load)
62 examples, 17 failures

Failed examples:

rspec ./spec/metaschema_spec.rb[1:1:1:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/allowed-values/allowed-values-basic_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:3:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/collapsible/collapsible-no-op_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:4:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/collapsible/collapsible_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:11:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/dates-times/datatypes-date_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:12:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/dates-times/datatypes-datetime-no-tz_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:13:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/dates-times/datatypes-datetime_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:21:1] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/group-as/group-as-misc_metaschema.xml provides identical attribute access
rspec ./spec/metaschema_spec.rb[1:1:21:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/group-as/group-as-misc_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:26:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/global-and-local_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:27:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/global-and-scoped-local_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:28:1] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/modular_metaschema.xml provides identical attribute access
rspec ./spec/metaschema_spec.rb[1:1:28:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/modular_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:29:1] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/modules/module_metaschema.xml provides identical attribute access
rspec ./spec/metaschema_spec.rb[1:1:29:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/modules/module_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:30:2] # Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/token/datatypes-token_metaschema.xml performs lossless round-trip conversion
rspec ./spec/metaschema_spec.rb[1:1:31:1] # Metaschema XML round-trip conversion with file metaschema/examples/computer-example.xml provides identical attribute access
rspec ./spec/metaschema_spec.rb[1:1:31:2] # Metaschema XML round-trip conversion with file metaschema/examples/computer-example.xml performs lossless round-trip conversion
```

**Comment by ronaldtse** [comment]
### The tests that fail on `attributes is nil`

Is due to this:

```
irb(main):001> parsed = Metaschema::Root.from_xml(IO.read('spec/fixtures/metaschema/test-suite/schema-generation/local-declarations/modular_metaschema.xml'))
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:379:in `initialize': undefined method `attributes' for nil (NoMethodError)

        return unless self.class.attributes
                                ^^^^^^^^^^^
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:258:in `new'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:258:in `apply_mappings'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/attribute.rb:65:in `cast'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:339:in `block in apply_xml_mapping'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:316:in `each'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:316:in `apply_xml_mapping'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:260:in `apply_mappings'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:99:in `block (2 levels) in <module:ClassMethods>'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:89:in `public_send'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.8/lib/lutaml/model/serialize.rb:89:in `block (2 levels) in <module:ClassMethods>'
	from (irb):1:in `<main>'
	from <internal:kernel>:187:in `loop'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/cli/console.rb:20:in `run'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:486:in `console'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from ~/.asdf/installs/ruby/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	... 9 levels...
```

I'm not sure which exact line/element/attribute causes it to fail, here's one of the files:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- validate with XSD and Schematron (linked) -->
<?xml-model href="../../../toolchains/xslt-M4/validate/metaschema-composition-check.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0">
   <schema-name>OSCAL Control Catalog Format</schema-name>
   <schema-version>1.0.0-milestone3</schema-version>
   <short-name>oscal-catalog</short-name>
   <namespace>http://csrc.nist.gov/ns/metaschema/test</namespace>
   <json-base-uri>http://csrc.nist.gov/ns/metaschema/test</json-base-uri>
   <remarks>
      <p>For exercising Metaschema semantics with respect to modular assembly and composition.</p>
   </remarks>
  
   <import href="modules/module_metaschema.xml"/>
   
   <define-assembly name="root">
      <formal-name>Nominal root</formal-name>
      <description>XXX</description>
      <root-name>root-assembly</root-name>
      <flag ref="top-level-flag"/>
      <define-flag name="local-flag">
         <formal-name>Locally defined flag</formal-name>
         <description>XXX</description>
      </define-flag>
      <model>
         <field ref="top-level-global-field"/>
         <field ref="top-level-local-field"/>
         <define-field name="local-field">
            <formal-name>Locally defined field</formal-name>
            <description>XXX</description>
         </define-field>
      </model>
   </define-assembly>
   
   <define-field name="top-level-global-field">
      <formal-name>Field, defined at top level (global by default)</formal-name>
      <description>XXX</description>
   </define-field>
   
   <define-field name="top-level-local-field" scope="local">
      <formal-name>Field, defined at top level as 'local'</formal-name>
      <description>XXX</description>
   </define-field>
   
   <define-flag name="top-level-flag">
      <formal-name>Flag, defined at top level</formal-name>
      <description>XXX</description>
   </define-flag>
   
</METASCHEMA>
```

## Tests that fail on element order

```
  6) Metaschema XML round-trip conversion with file /Users/mulgogi/src/lutaml/metaschema/spec/fixtures/metaschema/test-suite/schema-generation/dates-times/datatypes-datetime_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <assembly ref="child" max-occurs="unbounded">
               <group-as name="children"/>
             </assembly>
               actual node  : <field ref="field-datetime" max-occurs="unbounded">
                   <group-as name="field-datetimes"/>
                </field>
               diff from    : assembly
               diff to      : field
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'
```

```
       DIFF 1: expected node: <flag ref="global-flag"/>
               actual node  : <define-flag name="local-flag" as-type="token">
                <formal-name>Flag defined locally</formal-name>
                <description>Has a local definition</description>
             </define-flag>
               diff from    : flag
               diff to      : define-flag
     
       DIFF 2: expected node: <define-assembly name="global-assembly">
           <formal-name>Assembly defined globally</formal-name>
           <description>Has a global definition</description>
           <model>
             <field ref="global-field"/>
             <define-field as-type="string" name="local-field2">
               <formal-name>Field defined locally</formal-name>
               <description>Has a local definition</description>
             </define-field>
           </model>
         </define-assembly>
               actual node  : <define-flag name="global-flag" as-type="token">
             <formal-name>Flag defined globally</formal-name>
             <description>Has a global definition</description>
          </define-flag>
               diff from    : define-assembly
               diff to      : define-flag
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'
```

These specs fail because the generated output uses a different element order at the same level.

**Comment by ronaldtse** [comment]
## Failure due to missing `xsi:schemaLocation`

This spec contains `xsi:schemaLocation` and therefore the `xmlns:xsi` namespace declaration. However the rendered element is missing it:

```
  15) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/token/datatypes-token_metaschema.xml performs lossless round-trip conversion
      Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
      
        DIFF 1: expected node: <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0">
          <schema-name>Metaschema Unit Test: Token Datatype</schema-name>
          <schema-version>1.0-milestone2</schema-version>
          <short-name>metaschema-datatypes-token</short-name>
          <namespace>http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-uri</namespace>
          <json-base-uri>http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-uri</json-base-uri>
          <define-assembly name="parent">
            <formal-name>parent</formal-name>
            <description>parent assembly</description>
            <root-name>parent</root-name>
            <define-flag name="token-flag" as-type="token" required="yes">
              <formal-name>A metaschema 'token', a string without spaces suitable for use as a key value)</formal-name>
              <description>Corresponds to XML NCName (no-colon name).</description>
            </define-flag>
            <model>
              <field ref="token-field" max-occurs="unbounded">
                <group-as name="token-fields"/>
              </field>
            </model>
          </define-assembly>
          <define-field as-type="token" name="token-field">
            <formal-name>A metaschema 'token', a string without spaces for use as a key value</formal-name>
            <description>Corresponds to XML NCName (no-colon name).</description>
          </define-field>
        </METASCHEMA>
                actual node  : <METASCHEMA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.0 ../../../toolchains/xslt-M4/validate/metaschema.xsd">
          <schema-name>Metaschema Unit Test: Token Datatype</schema-name>
          <schema-version>1.0-milestone2</schema-version>
          <short-name>metaschema-datatypes-token</short-name>
          <namespace>http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-uri</namespace>
          <json-base-uri>http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-uri</json-base-uri>
         
          <define-assembly name="parent">
            <formal-name>parent</formal-name>
            <description>parent assembly</description>
            <root-name>parent</root-name>
            <define-flag name="token-flag" as-type="token" required="yes">
              <formal-name>A metaschema 'token', a string without spaces suitable for use as a key value)</formal-name>
              <description>Corresponds to XML NCName (no-colon name).</description>
            </define-flag>
            <model>
              <field ref="token-field" max-occurs="unbounded">
                <group-as name="token-fields"/>
              </field>
            </model>
          </define-assembly>
      
          <define-field name="token-field" as-type="token">
            <formal-name>A metaschema 'token', a string without spaces for use as a key value</formal-name>
            <description>Corresponds to XML NCName (no-colon name).</description>
          </define-field>
          
        </METASCHEMA>
                diff from    : 
                diff to      : schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.0 ../../../toolchains/xslt-M4/validate/metaschema.xsd"
      # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'
```

**Comment by ronaldtse** [comment]
Closing as all described tests fixed. The remaining tests are due to:
* https://github.com/lutaml/lutaml-model/issues/111
* https://github.com/lutaml/lutaml-model/issues/110

Those will be separate issues.
