### ISSUE TITLE
Fix specs that fail on element order

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/metaschema#6]
We need to have a way to tell lutaml-model to retain element order as it comes in?

Tests that fail on element order:

```
  6) Metaschema XML round-trip conversion with file /Users/mulgogi/src/lutaml/metaschema/spec/fixtures/metaschema/test-suite/schema-generation/dates-times/datatypes-datetime_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <assembly ref="child" max-occurs="unbounded">
               <group-as name="children"/>
             </assembly>
               actual node  : <field ref="field-datetime" max-occurs="unbounded">
                   <group-as name="field-datetimes"/>
                </field>
               diff from    : assembly
               diff to      : field
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'
```

```
       DIFF 1: expected node: <flag ref="global-flag"/>
               actual node  : <define-flag name="local-flag" as-type="token">
                <formal-name>Flag defined locally</formal-name>
                <description>Has a local definition</description>
             </define-flag>
               diff from    : flag
               diff to      : define-flag
     
       DIFF 2: expected node: <define-assembly name="global-assembly">
           <formal-name>Assembly defined globally</formal-name>
           <description>Has a global definition</description>
           <model>
             <field ref="global-field"/>
             <define-field as-type="string" name="local-field2">
               <formal-name>Field defined locally</formal-name>
               <description>Has a local definition</description>
             </define-field>
           </model>
         </define-assembly>
               actual node  : <define-flag name="global-flag" as-type="token">
             <formal-name>Flag defined globally</formal-name>
             <description>Has a global definition</description>
          </define-flag>
               diff from    : define-assembly
               diff to      : define-flag
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'
```

These specs fail because the generated output uses a different element order at the same level.

_Originally posted by @ronaldtse in https://github.com/lutaml/metaschema/issues/3#issuecomment-2423799190_

**Comment by ronaldtse** [comment]
@HassanAkbar is this related to this:
* https://github.com/lutaml/lutaml-model/issues/4 ?

**Comment by HassanAkbar** [comment]
@ronaldtse we need to set `mixed: true` to retain elements order. I'm looking into it right now.

**Comment by ronaldtse** [comment]
@HassanAkbar but that's very strange, that we have to set `mixed: true` because there is no textual content in between these elements. These are unit elements that just have an order. Can we separate these two concerns, i.e. intermingled text vs element order, so I can just use element order without the intermingled text?

**Comment by HassanAkbar** [comment]
@ronaldtse Sure, I can alias it to something more fitting.
Does `ordered: true` sounds good to you?

**Comment by ronaldtse** [comment]
`ordered: true` sounds good. But I'm not sure an "alias" is what we want?

`mixed: true`
```xml
<a>hello</a>  xxx <b>foo</b>
```
=> 
```ruby
a => hello
b => foo
root => [#a<...>, "  xxx  ", #b<...>]
```

And `ordered: true`

```xml
<a>hello</a>  xxx <b>foo</b>
```
=> 
```ruby
a => hello
b => foo
root => [#a<...>, #b<...>]
```

Are different cases?

**Comment by HassanAkbar** [comment]
@ronaldtse From what I understand, we need an `ordered: true` attribute that will only keep the order of the elements and not the `text`.
I'll open a PR for this in `lutaml-model` and will let you know.

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar ! We need to apply the `ordered: true` here. The gem has been released.
